version: 2.1

workflows:
  main:
    jobs:
      - build:
          context: [DOCKERHUB]
          project_names: "dotnet6-aws2"

jobs:
  build:
    parameters:
      project_names:
        type: string
    working_directory: /app
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          keys:
            - v1-{{ .Branch }}
          paths:
            - /caches/app.tar
      - run:
          name: Load Docker image layer cache
          command: |
            set +o pipefail
            docker load -i /caches/app.tar | true
      - run:
          name: Build Docker images
          command: |
            docker_files="<< parameters.project_names >>"
            for docker_file in $(echo "$docker_files" | tr ',' ' ')
            do
              docker build --cache-from=app -t $docker_file -f ./$docker_file .;
            done
      - run:
          name: Save Docker image layer cache
          command: |
            mkdir -p /caches
            docker save -o /caches/app.tar app
      - save_cache:
          key: v1-{{ .Branch }}-{{ epoch }}
          paths:
            - /caches/app.tar
      - run:
          name: Push Docker images
          command: |
            #if [ "${CIRCLE_BRANCH}" == "master" ]; then
              echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
              
            docker_files="<< parameters.project_names >>"
            for docker_file in $(echo "$docker_files" | tr ',' ' ')
            do
              docker push $docker_file
            done
            #fi